# Generated by Django 3.2.5 on 2021-08-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
