# Generated by Django 3.2.6 on 2021-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='bio',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
