# Generated by Django 3.2.6 on 2021-08-06 14:11

from django.db import migrations, models
import model_extra.models


class Migration(migrations.Migration):

    dependencies = [
        ('model_extra', '0002_alter_userbio_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbio',
            name='age',
            field=models.IntegerField(validators=[model_extra.models.validate_my_age]),
        ),
    ]
