# Generated by Django 3.2.5 on 2021-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_relation', '0003_alter_userdetails_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='country',
            field=models.ManyToManyField(to='model_relation.Country'),
        ),
    ]
