# Generated by Django 3.2.5 on 2021-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_relation', '0004_auto_20210809_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('update_at', models.DateTimeField()),
                ('info', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]

